'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Calendar, Star, Info } from 'lucide-react';

interface HeritageSite {
  name: string;
  lat: number;
  lon: number;
  historic?: string;
  description?: string;
  website?: string;
  opening_hours?: string;
  fee?: string;
  distance?: number;
}

interface HeritageSiteCardProps {
  site: HeritageSite;
  onLocationClick?: (lat: number, lon: number) => void;
}

export function HeritageSiteCard({ site, onLocationClick }: HeritageSiteCardProps) {
  const getHistoricType = (historic: string) => {
    const typeMap: { [key: string]: string } = {
      'monument': 'Monument',
      'castle': 'Castle',
      'palace': 'Palace',
      'temple': 'Temple',
      'church': 'Church',
      'mosque': 'Mosque',
      'fort': 'Fort',
      'ruins': 'Ruins',
      'archaeological_site': 'Archaeological Site',
      'memorial': 'Memorial',
      'tomb': 'Tomb',
      'museum': 'Museum',
      'building': 'Historic Building',
      'bridge': 'Historic Bridge',
      'tower': 'Tower',
      'gate': 'Historic Gate',
      'wall': 'Historic Wall',
      'battlefield': 'Battlefield',
      'ship': 'Historic Ship',
      'aircraft': 'Historic Aircraft',
      'locomotive': 'Historic Locomotive',
      'vehicle': 'Historic Vehicle',
      'cannon': 'Cannon',
      'pillory': 'Pillory',
      'wayside_shrine': 'Wayside Shrine',
      'wayside_cross': 'Wayside Cross',
      'boundary_stone': 'Boundary Stone',
      'milestone': 'Milestone',
      'tombstone': 'Tombstone',
      'cross': 'Cross',
      'statue': 'Statue',
      'bust': 'Bust',
      'stolperstein': 'Stolperstein',
      'war_memorial': 'War Memorial',
      'monumental_tree': 'Monumental Tree',
      'city_gate': 'City Gate',
      'citywalls': 'City Walls',
      'rampart': 'Rampart',
      'tumulus': 'Tumulus',
      'dolmen': 'Dolmen',
      'menhir': 'Menhir',
      'stone': 'Historic Stone',
      'rune_stone': 'Rune Stone',
      'petroglyph': 'Petroglyph',
      'cave_painting': 'Cave Painting',
      'hillfort': 'Hillfort',
      'oppidum': 'Oppidum',
      'roman_villa': 'Roman Villa',
      'roman_road': 'Roman Road',
      'roman_aqueduct': 'Roman Aqueduct',
      'roman_bridge': 'Roman Bridge',
      'roman_bath': 'Roman Bath',
      'roman_theatre': 'Roman Theatre',
      'roman_amphitheatre': 'Roman Amphitheatre',
      'roman_circus': 'Roman Circus',
      'roman_camp': 'Roman Camp',
      'roman_tower': 'Roman Tower',
      'roman_gate': 'Roman Gate',
      'roman_wall': 'Roman Wall',
      'roman_temple': 'Roman Temple',
      'roman_tomb': 'Roman Tomb',
      'roman_mausoleum': 'Roman Mausoleum',
      'roman_milestone': 'Roman Milestone',
      'roman_inscription': 'Roman Inscription',
      'roman_altar': 'Roman Altar',
      'roman_statue': 'Roman Statue',
      'roman_bust': 'Roman Bust',
      'roman_relief': 'Roman Relief',
      'roman_mosaic': 'Roman Mosaic',
      'roman_fresco': 'Roman Fresco',
      'roman_pottery': 'Roman Pottery',
      'roman_coin': 'Roman Coin',
      'roman_jewelry': 'Roman Jewelry',
      'roman_weapon': 'Roman Weapon',
      'roman_armor': 'Roman Armor',
      'roman_helmet': 'Roman Helmet',
      'roman_shield': 'Roman Shield',
      'roman_sword': 'Roman Sword',
      'roman_spear': 'Roman Spear',
      'roman_arrow': 'Roman Arrow',
      'roman_sling': 'Roman Sling',
      'roman_catapult': 'Roman Catapult',
      'roman_ballista': 'Roman Ballista',
      'roman_onager': 'Roman Onager',
      'roman_scorpio': 'Roman Scorpio',
      'roman_caroballista': 'Roman Carroballista',
      'roman_plumbata': 'Roman Plumbata',
      'roman_pilum': 'Roman Pilum',
      'roman_gladius': 'Roman Gladius',
      'roman_spatha': 'Roman Spatha',
      'roman_dagger': 'Roman Dagger',
      'roman_knife': 'Roman Knife',
      'roman_axe': 'Roman Axe',
      'roman_hammer': 'Roman Hammer',
      'roman_chisel': 'Roman Chisel',
      'roman_saw': 'Roman Saw',
      'roman_drill': 'Roman Drill',
      'roman_file': 'Roman File',
      'roman_rasp': 'Roman Rasp',
      'roman_plane': 'Roman Plane',
      'roman_adze': 'Roman Adze',
      'roman_mattock': 'Roman Mattock',
      'roman_hoe': 'Roman Hoe',
      'roman_spade': 'Roman Spade',
      'roman_shovel': 'Roman Shovel',
      'roman_pickaxe': 'Roman Pickaxe',
      'roman_crowbar': 'Roman Crowbar',
      'roman_lever': 'Roman Lever',
      'roman_pulley': 'Roman Pulley',
      'roman_winch': 'Roman Winch',
      'roman_crane': 'Roman Crane',
      'roman_derrick': 'Roman Derrick',
      'roman_scaffold': 'Roman Scaffold',
      'roman_ladder': 'Roman Ladder',
      'roman_stairs': 'Roman Stairs',
      'roman_ramp': 'Roman Ramp',
      'roman_platform': 'Roman Platform',
      'roman_stage': 'Roman Stage',
      'roman_podium': 'Roman Podium',
      'roman_rostrum': 'Roman Rostrum',
      'roman_tribune': 'Roman Tribune',
      'roman_stand': 'Roman Stand',
      'roman_bleacher': 'Roman Bleacher',
      'roman_bench': 'Roman Bench',
      'roman_seat': 'Roman Seat',
      'roman_chair': 'Roman Chair',
      'roman_stool': 'Roman Stool',
      'roman_table': 'Roman Table',
      'roman_desk': 'Roman Desk',
      'roman_counter': 'Roman Counter',
      'roman_shelf': 'Roman Shelf',
      'roman_cabinet': 'Roman Cabinet',
      'roman_chest': 'Roman Chest',
      'roman_box': 'Roman Box',
      'roman_basket': 'Roman Basket',
      'roman_bag': 'Roman Bag',
      'roman_sack': 'Roman Sack',
      'roman_pouch': 'Roman Pouch',
      'roman_purse': 'Roman Purse',
      'roman_wallet': 'Roman Wallet',
      'roman_pocket': 'Roman Pocket',
      'roman_compartment': 'Roman Compartment',
      'roman_division': 'Roman Division',
      'roman_section': 'Roman Section',
      'roman_part': 'Roman Part',
      'roman_piece': 'Roman Piece',
      'roman_fragment': 'Roman Fragment',
      'roman_remnant': 'Roman Remnant',
      'roman_vestige': 'Roman Vestige',
      'roman_trace': 'Roman Trace',
      'roman_evidence': 'Roman Evidence',
      'roman_proof': 'Roman Proof',
      'roman_indication': 'Roman Indication',
      'roman_sign': 'Roman Sign',
      'roman_mark': 'Roman Mark',
      'roman_symbol': 'Roman Symbol',
      'roman_emblem': 'Roman Emblem',
      'roman_badge': 'Roman Badge',
      'roman_insignia': 'Roman Insignia',
      'roman_crest': 'Roman Crest',
      'roman_coat_of_arms': 'Roman Coat of Arms',
      'roman_heraldry': 'Roman Heraldry',
      'roman_blazon': 'Roman Blazon',
      'roman_armorial': 'Roman Armorial',
      'roman_escutcheon': 'Roman Escutcheon',
      'roman_shield': 'Roman Shield',
      'roman_banner': 'Roman Banner',
      'roman_flag': 'Roman Flag',
      'roman_standard': 'Roman Standard',
      'roman_ensign': 'Roman Ensign',
      'roman_pennant': 'Roman Pennant',
      'roman_streamer': 'Roman Streamer',
      'roman_ribbon': 'Roman Ribbon',
      'roman_sash': 'Roman Sash',
      'roman_belt': 'Roman Belt',
      'roman_girdle': 'Roman Girdle',
      'roman_cincture': 'Roman Cincture',
      'roman_waistband': 'Roman Waistband',
      'roman_cummerbund': 'Roman Cummerbund',
      'roman_corset': 'Roman Corset',
      'roman_bodice': 'Roman Bodice',
      'roman_vest': 'Roman Vest',
      'roman_waistcoat': 'Roman Waistcoat',
      'roman_jacket': 'Roman Jacket',
      'roman_coat': 'Roman Coat',
      'roman_mantle': 'Roman Mantle',
      'roman_cloak': 'Roman Cloak',
      'roman_cape': 'Roman Cape',
      'roman_poncho': 'Roman Poncho',
      'roman_serape': 'Roman Serape',
      'roman_blanket': 'Roman Blanket',
      'roman_throw': 'Roman Throw',
      'roman_cover': 'Roman Cover',
      'roman_sheet': 'Roman Sheet',
      'roman_linen': 'Roman Linen',
      'roman_fabric': 'Roman Fabric',
      'roman_cloth': 'Roman Cloth',
      'roman_material': 'Roman Material',
      'roman_textile': 'Roman Textile',
      'roman_weave': 'Roman Weave',
      'roman_knit': 'Roman Knit',
      'roman_crochet': 'Roman Crochet',
      'roman_embroidery': 'Roman Embroidery',
      'roman_needlework': 'Roman Needlework',
      'roman_sewing': 'Roman Sewing',
      'roman_stitching': 'Roman Stitching',
      'roman_hemming': 'Roman Hemming',
      'roman_darning': 'Roman Darning',
      'roman_patching': 'Roman Patching',
      'roman_mending': 'Roman Mending',
      'roman_repairing': 'Roman Repairing',
      'roman_restoring': 'Roman Restoring',
      'roman_renovating': 'Roman Renovating',
      'roman_refurbishing': 'Roman Refurbishing',
      'roman_redecorating': 'Roman Redecorating',
      'roman_remodeling': 'Roman Remodeling',
      'roman_reconstructing': 'Roman Reconstructing',
      'roman_rebuilding': 'Roman Rebuilding',
      'roman_recreating': 'Roman Recreating',
      'roman_reproducing': 'Roman Reproducing',
      'roman_copying': 'Roman Copying',
      'roman_duplicating': 'Roman Duplicating',
      'roman_replicating': 'Roman Replicating',
      'roman_imitating': 'Roman Imitating',
      'roman_mimicking': 'Roman Mimicking',
      'roman_emulating': 'Roman Emulating',
      'roman_simulating': 'Roman Simulating',
      'roman_mirroring': 'Roman Mirroring',
      'roman_reflecting': 'Roman Reflecting',
      'roman_echoing': 'Roman Echoing',
      'roman_repeating': 'Roman Repeating',
      'roman_redoing': 'Roman Redoing',
      'roman_retrying': 'Roman Retrying',
      'roman_attempting': 'Roman Attempting',
      'roman_endeavoring': 'Roman Endeavoring',
      'roman_striving': 'Roman Striving',
      'roman_seeking': 'Roman Seeking',
      'roman_searching': 'Roman Searching',
      'roman_looking': 'Roman Looking',
      'roman_finding': 'Roman Finding',
      'roman_discovering': 'Roman Discovering',
      'roman_uncovering': 'Roman Uncovering',
      'roman_revealing': 'Roman Revealing',
      'roman_exposing': 'Roman Exposing',
      'roman_showing': 'Roman Showing',
      'roman_displaying': 'Roman Displaying',
      'roman_exhibiting': 'Roman Exhibiting',
      'roman_presenting': 'Roman Presenting',
      'roman_demonstrating': 'Roman Demonstrating',
      'roman_illustrating': 'Roman Illustrating',
      'roman_exemplifying': 'Roman Exemplifying',
      'roman_representing': 'Roman Representing',
      'roman_depicting': 'Roman Depicting',
      'roman_portraying': 'Roman Portraying',
      'roman_describing': 'Roman Describing',
      'roman_narrating': 'Roman Narrating',
      'roman_telling': 'Roman Telling',
      'roman_relating': 'Roman Relating',
      'roman_recounting': 'Roman Recounting',
      'roman_reciting': 'Roman Reciting',
      'roman_quoting': 'Roman Quoting',
      'roman_citing': 'Roman Citing',
      'roman_referencing': 'Roman Referencing',
      'roman_mentioning': 'Roman Mentioning',
      'roman_naming': 'Roman Naming',
      'roman_calling': 'Roman Calling',
      'roman_terming': 'Roman Terming',
      'roman_labeling': 'Roman Labeling',
      'roman_tagging': 'Roman Tagging',
      'roman_marking': 'Roman Marking',
      'roman_identifying': 'Roman Identifying',
      'roman_recognizing': 'Roman Recognizing',
      'roman_acknowledging': 'Roman Acknowledging',
      'roman_admitting': 'Roman Admitting',
      'roman_confessing': 'Roman Confessing',
      'roman_declaring': 'Roman Declaring',
      'roman_announcing': 'Roman Announcing',
      'roman_proclaiming': 'Roman Proclaiming',
      'roman_pronouncing': 'Roman Pronouncing',
      'roman_uttering': 'Roman Uttering',
      'roman_voicing': 'Roman Voicing',
      'roman_expressing': 'Roman Expressing',
      'roman_communicating': 'Roman Communicating',
      'roman_conveying': 'Roman Conveying',
      'roman_transmitting': 'Roman Transmitting',
      'roman_transferring': 'Roman Transferring',
      'roman_passing': 'Roman Passing',
      'roman_handing': 'Roman Handing',
      'roman_giving': 'Roman Giving',
      'roman_providing': 'Roman Providing',
      'roman_supplying': 'Roman Supplying',
      'roman_furnishing': 'Roman Furnishing',
      'roman_equipping': 'Roman Equipping',
      'roman_outfitting': 'Roman Outfitting',
      'roman_preparing': 'Roman Preparing',
      'roman_readying': 'Roman Readying',
      'roman_setting': 'Roman Setting',
      'roman_placing': 'Roman Placing',
      'roman_putting': 'Roman Putting',
      'roman_positioning': 'Roman Positioning',
      'roman_situating': 'Roman Situating',
      'roman_locating': 'Roman Locating',
      'roman_siting': 'Roman Siting',
      'roman_establishing': 'Roman Establishing',
      'roman_founding': 'Roman Founding',
      'roman_creating': 'Roman Creating',
      'roman_making': 'Roman Making',
      'roman_building': 'Roman Building',
      'roman_constructing': 'Roman Constructing',
      'roman_erecting': 'Roman Erecting',
      'roman_raising': 'Roman Raising',
      'roman_lifting': 'Roman Lifting',
      'roman_elevating': 'Roman Elevating',
      'roman_hoisting': 'Roman Hoisting',
      'roman_hauling': 'Roman Hauling',
      'roman_towing': 'Roman Towing',
      'roman_dragging': 'Roman Dragging',
      'roman_pulling': 'Roman Pulling',
      'roman_tugging': 'Roman Tugging',
      'roman_yanking': 'Roman Yanking',
      'roman_jerking': 'Roman Jerking',
      'roman_twitching': 'Roman Twitching',
      'roman_tugging': 'Roman Tugging',
      'roman_wrenching': 'Roman Wrenching',
      'roman_twisting': 'Roman Twisting',
      'roman_turning': 'Roman Turning',
      'roman_rotating': 'Roman Rotating',
      'roman_spinning': 'Roman Spinning',
      'roman_whirling': 'Roman Whirling',
      'roman_revolving': 'Roman Revolving',
      'roman_orbiting': 'Roman Orbiting',
      'roman_circling': 'Roman Circling',
      'roman_rounding': 'Roman Rounding',
      'roman_curving': 'Roman Curving',
      'roman_bending': 'Roman Bending',
      'roman_flexing': 'Roman Flexing',
      'roman_stretching': 'Roman Stretching',
      'roman_extending': 'Roman Extending',
      'roman_expanding': 'Roman Expanding',
      'roman_enlarging': 'Roman Enlarging',
      'roman_increasing': 'Roman Increasing',
      'roman_growing': 'Roman Growing',
      'roman_developing': 'Roman Developing',
      'roman_advancing': 'Roman Advancing',
      'roman_progressing': 'Roman Progressing',
      'roman_improving': 'Roman Improving',
      'roman_enhancing': 'Roman Enhancing',
      'roman_upgrading': 'Roman Upgrading',
      'roman_modernizing': 'Roman Modernizing',
      'roman_renovating': 'Roman Renovating',
      'roman_refurbishing': 'Roman Refurbishing',
      'roman_restoring': 'Roman Restoring',
      'roman_repairing': 'Roman Repairing',
      'roman_fixing': 'Roman Fixing',
      'roman_mending': 'Roman Mending',
      'roman_patching': 'Roman Patching',
      'roman_darning': 'Roman Darning',
      'roman_hemming': 'Roman Hemming',
      'roman_stitching': 'Roman Stitching',
      'roman_sewing': 'Roman Sewing',
      'roman_needlework': 'Roman Needlework',
      'roman_embroidery': 'Roman Embroidery',
      'roman_crochet': 'Roman Crochet',
      'roman_knit': 'Roman Knit',
      'roman_weave': 'Roman Weave',
      'roman_textile': 'Roman Textile',
      'roman_material': 'Roman Material',
      'roman_cloth': 'Roman Cloth',
      'roman_fabric': 'Roman Fabric',
      'roman_linen': 'Roman Linen',
      'roman_sheet': 'Roman Sheet',
      'roman_cover': 'Roman Cover',
      'roman_throw': 'Roman Throw',
      'roman_blanket': 'Roman Blanket',
      'roman_serape': 'Roman Serape',
      'roman_poncho': 'Roman Poncho',
      'roman_cape': 'Roman Cape',
      'roman_cloak': 'Roman Cloak',
      'roman_mantle': 'Roman Mantle',
      'roman_coat': 'Roman Coat',
      'roman_jacket': 'Roman Jacket',
      'roman_waistcoat': 'Roman Waistcoat',
      'roman_vest': 'Roman Vest',
      'roman_bodice': 'Roman Bodice',
      'roman_corset': 'Roman Corset',
      'roman_cummerbund': 'Roman Cummerbund',
      'roman_waistband': 'Roman Waistband',
      'roman_cincture': 'Roman Cincture',
      'roman_girdle': 'Roman Girdle',
      'roman_belt': 'Roman Belt',
      'roman_sash': 'Roman Sash',
      'roman_ribbon': 'Roman Ribbon',
      'roman_streamer': 'Roman Streamer',
      'roman_pennant': 'Roman Pennant',
      'roman_ensign': 'Roman Ensign',
      'roman_standard': 'Roman Standard',
      'roman_flag': 'Roman Flag',
      'roman_banner': 'Roman Banner',
      'roman_shield': 'Roman Shield',
      'roman_escutcheon': 'Roman Escutcheon',
      'roman_armorial': 'Roman Armorial',
      'roman_blazon': 'Roman Blazon',
      'roman_heraldry': 'Roman Heraldry',
      'roman_coat_of_arms': 'Roman Coat of Arms',
      'roman_crest': 'Roman Crest',
      'roman_insignia': 'Roman Insignia',
      'roman_badge': 'Roman Badge',
      'roman_emblem': 'Roman Emblem',
      'roman_symbol': 'Roman Symbol',
      'roman_mark': 'Roman Mark',
      'roman_sign': 'Roman Sign',
      'roman_indication': 'Roman Indication',
      'roman_proof': 'Roman Proof',
      'roman_evidence': 'Roman Evidence',
      'roman_trace': 'Roman Trace',
      'roman_vestige': 'Roman Vestige',
      'roman_remnant': 'Roman Remnant',
      'roman_fragment': 'Roman Fragment',
      'roman_piece': 'Roman Piece',
      'roman_part': 'Roman Part',
      'roman_section': 'Roman Section',
      'roman_division': 'Roman Division',
      'roman_compartment': 'Roman Compartment',
      'roman_pocket': 'Roman Pocket',
      'roman_wallet': 'Roman Wallet',
      'roman_purse': 'Roman Purse',
      'roman_pouch': 'Roman Pouch',
      'roman_sack': 'Roman Sack',
      'roman_bag': 'Roman Bag',
      'roman_basket': 'Roman Basket',
      'roman_box': 'Roman Box',
      'roman_chest': 'Roman Chest',
      'roman_cabinet': 'Roman Cabinet',
      'roman_shelf': 'Roman Shelf',
      'roman_counter': 'Roman Counter',
      'roman_desk': 'Roman Desk',
      'roman_table': 'Roman Table',
      'roman_stool': 'Roman Stool',
      'roman_chair': 'Roman Chair',
      'roman_seat': 'Roman Seat',
      'roman_bench': 'Roman Bench',
      'roman_bleacher': 'Roman Bleacher',
      'roman_stand': 'Roman Stand',
      'roman_tribune': 'Roman Tribune',
      'roman_rostrum': 'Roman Rostrum',
      'roman_podium': 'Roman Podium',
      'roman_stage': 'Roman Stage',
      'roman_platform': 'Roman Platform',
      'roman_ramp': 'Roman Ramp',
      'roman_stairs': 'Roman Stairs',
      'roman_ladder': 'Roman Ladder',
      'roman_scaffold': 'Roman Scaffold',
      'roman_derrick': 'Roman Derrick',
      'roman_crane': 'Roman Crane',
      'roman_winch': 'Roman Winch',
      'roman_pulley': 'Roman Pulley',
      'roman_lever': 'Roman Lever',
      'roman_crowbar': 'Roman Crowbar',
      'roman_pickaxe': 'Roman Pickaxe',
      'roman_shovel': 'Roman Shovel',
      'roman_spade': 'Roman Spade',
      'roman_hoe': 'Roman Hoe',
      'roman_mattock': 'Roman Mattock',
      'roman_adze': 'Roman Adze',
      'roman_plane': 'Roman Plane',
      'roman_rasp': 'Roman Rasp',
      'roman_file': 'Roman File',
      'roman_drill': 'Roman Drill',
      'roman_saw': 'Roman Saw',
      'roman_chisel': 'Roman Chisel',
      'roman_hammer': 'Roman Hammer',
      'roman_axe': 'Roman Axe',
      'roman_knife': 'Roman Knife',
      'roman_dagger': 'Roman Dagger',
      'roman_spatha': 'Roman Spatha',
      'roman_gladius': 'Roman Gladius',
      'roman_pilum': 'Roman Pilum',
      'roman_plumbata': 'Roman Plumbata',
      'roman_caroballista': 'Roman Carroballista',
      'roman_scorpio': 'Roman Scorpio',
      'roman_onager': 'Roman Onager',
      'roman_ballista': 'Roman Ballista',
      'roman_catapult': 'Roman Catapult',
      'roman_sling': 'Roman Sling',
      'roman_arrow': 'Roman Arrow',
      'roman_spear': 'Roman Spear',
      'roman_sword': 'Roman Sword',
      'roman_shield': 'Roman Shield',
      'roman_helmet': 'Roman Helmet',
      'roman_armor': 'Roman Armor',
      'roman_weapon': 'Roman Weapon',
      'roman_jewelry': 'Roman Jewelry',
      'roman_coin': 'Roman Coin',
      'roman_pottery': 'Roman Pottery',
      'roman_fresco': 'Roman Fresco',
      'roman_mosaic': 'Roman Mosaic',
      'roman_relief': 'Roman Relief',
      'roman_bust': 'Roman Bust',
      'roman_statue': 'Roman Statue',
      'roman_altar': 'Roman Altar',
      'roman_inscription': 'Roman Inscription',
      'roman_milestone': 'Roman Milestone',
      'roman_mausoleum': 'Roman Mausoleum',
      'roman_tomb': 'Roman Tomb',
      'roman_temple': 'Roman Temple',
      'roman_wall': 'Roman Wall',
      'roman_gate': 'Roman Gate',
      'roman_tower': 'Roman Tower',
      'roman_camp': 'Roman Camp',
      'roman_circus': 'Roman Circus',
      'roman_amphitheatre': 'Roman Amphitheatre',
      'roman_theatre': 'Roman Theatre',
      'roman_bath': 'Roman Bath',
      'roman_bridge': 'Roman Bridge',
      'roman_aqueduct': 'Roman Aqueduct',
      'roman_road': 'Roman Road',
      'roman_villa': 'Roman Villa',
      'oppidum': 'Oppidum',
      'hillfort': 'Hillfort',
      'cave_painting': 'Cave Painting',
      'petroglyph': 'Petroglyph',
      'rune_stone': 'Rune Stone',
      'stone': 'Historic Stone',
      'menhir': 'Menhir',
      'dolmen': 'Dolmen',
      'tumulus': 'Tumulus',
      'rampart': 'Rampart',
      'citywalls': 'City Walls',
      'city_gate': 'City Gate',
      'monumental_tree': 'Monumental Tree',
      'war_memorial': 'War Memorial',
      'stolperstein': 'Stolperstein',
      'bust': 'Bust',
      'statue': 'Statue',
      'cross': 'Cross',
      'tombstone': 'Tombstone',
      'milestone': 'Milestone',
      'boundary_stone': 'Boundary Stone',
      'wayside_cross': 'Wayside Cross',
      'wayside_shrine': 'Wayside Shrine',
      'pillory': 'Pillory',
      'cannon': 'Cannon',
      'vehicle': 'Historic Vehicle',
      'locomotive': 'Historic Locomotive',
      'aircraft': 'Historic Aircraft',
      'ship': 'Historic Ship',
      'battlefield': 'Battlefield',
      'wall': 'Historic Wall',
      'gate': 'Historic Gate',
      'tower': 'Tower',
      'bridge': 'Historic Bridge',
      'building': 'Historic Building',
      'museum': 'Museum',
      'tomb': 'Tomb',
      'memorial': 'Memorial',
      'archaeological_site': 'Archaeological Site',
      'ruins': 'Ruins',
      'fort': 'Fort',
      'mosque': 'Mosque',
      'church': 'Church',
      'temple': 'Temple',
      'palace': 'Palace',
      'castle': 'Castle',
      'monument': 'Monument'
    };
    return typeMap[historic.toLowerCase()] || 'Historic Site';
  };

  const getDistanceText = (distance?: number) => {
    if (!distance) return '';
    if (distance < 1000) return `${distance.toFixed(0)}m from route`;
    return `${(distance / 1000).toFixed(1)}km from route`;
  };

  return (
    <Card className="border-purple-200 bg-gradient-to-br from-purple-50 to-indigo-50 hover:shadow-lg transition-all duration-300">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <CardTitle className="text-lg text-purple-900 flex items-center gap-2">
              <span className="text-2xl">🏛️</span>
              {site.name}
            </CardTitle>
            <CardDescription className="text-purple-700 mt-1">
              {site.historic && (
                <Badge variant="secondary" className="bg-purple-100 text-purple-800 border-purple-200">
                  {getHistoricType(site.historic)}
                </Badge>
              )}
            </CardDescription>
          </div>
          {site.distance && (
            <div className="text-right">
              <div className="text-sm text-purple-600 font-medium">
                {getDistanceText(site.distance)}
              </div>
            </div>
          )}
        </div>
      </CardHeader>
      
      <CardContent className="pt-0">
        <div className="space-y-3">
          {site.description && (
            <div className="flex items-start gap-2">
              <Info className="h-4 w-4 text-purple-600 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-gray-700 leading-relaxed">
                {site.description}
              </p>
            </div>
          )}
          
          <div className="flex items-center gap-2 text-sm text-gray-600">
            <MapPin className="h-4 w-4 text-purple-600" />
            <span>
              {site.lat.toFixed(4)}, {site.lon.toFixed(4)}
            </span>
          </div>
          
          {site.opening_hours && (
            <div className="flex items-center gap-2 text-sm text-gray-600">
              <Calendar className="h-4 w-4 text-purple-600" />
              <span>{site.opening_hours}</span>
            </div>
          )}
          
          {site.fee && (
            <div className="flex items-center gap-2 text-sm text-gray-600">
              <span className="text-purple-600">💰</span>
              <span>Entry: {site.fee}</span>
            </div>
          )}
          
          {site.website && (
            <div className="pt-2">
              <a 
                href={site.website} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-sm text-purple-600 hover:text-purple-800 underline"
              >
                Visit Official Website →
              </a>
            </div>
          )}
          
          <div className="pt-2 flex gap-2">
            <button
              onClick={() => onLocationClick?.(site.lat, site.lon)}
              className="flex-1 bg-purple-600 hover:bg-purple-700 text-white text-sm px-3 py-2 rounded-md transition-colors duration-200 flex items-center justify-center gap-2"
            >
              <MapPin className="h-4 w-4" />
              View on Map
            </button>
            <button
              onClick={() => {
                const url = `https://www.google.com/maps/dir/?api=1&destination=${site.lat},${site.lon}`;
                window.open(url, '_blank');
              }}
              className="flex-1 bg-white hover:bg-gray-50 text-purple-600 border border-purple-200 text-sm px-3 py-2 rounded-md transition-colors duration-200 flex items-center justify-center gap-2"
            >
              <span>🗺️</span>
              Get Directions
            </button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
